package Biblioteca;


/**
* Biblioteca/GestionBibliotecaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* jueves 3 de abril de 2025 14H31' CEST
*/


// Define la interfaz para el sistema de gestión de la biblioteca
public interface GestionBibliotecaOperations 
{

  // Busca un libro por título y devuelve los detalles del libro
  Biblioteca.Libro buscarLibro (String titulo);

  // Presta un libro, cambiando su estado a no disponible
  boolean prestarLibro (String ISBN);

  // Devuelve un libro, cambiando su estado a disponible
  boolean devolverLibro (String ISBN);

  // Agrega un libro, cambiando su estado a disponible
  boolean agregarLibro (Biblioteca.Libro nuevoLibro);

  // Elimina un libro
  boolean eliminarLibro (String ISBN);

  //Listar libros segun el autor
  Biblioteca.Libro[] buscarPorAutor (String autor);

  //Listar todos los libros
  Biblioteca.Libro[] listarLibros ();
} // interface GestionBibliotecaOperations
